name: Write file
on:
  workflow_dispatch:
    inputs:
      path:
        description: "File path"
        required: true
        type: string
      content:
        description: "File content"
        required: true
        type: string

jobs:
  generate-addon:
    runs-on: ubuntu-latest
    name: "Write file"
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v3
      - name: Set github config
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      - name: Write to file
        uses: "DamianReeves/write-file-action@v1.2"
        with:
          path: src/static/${{ github.event.inputs.path }}
          write-mode: overwrite
          contents: ${{ github.event.inputs.content }}
      - name: Commit changes
        run: |
          git add .
          git commit -m "feat: update ${{ github.event.inputs.path }}"
      - name: Push changes
        run: git push